name: Snyk container workflow
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Snyk container test 
    - uses: actions/checkout@master
    - uses: snyk/actions/docker@0.3.0
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: node:16.9.0
        args: container --file=Dockerfile --sarif-file-output=hallo.sarif --app-vulns --nested-jars-depth=5
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: hallo.sarif
